
distributable:
  ## pre-built package download url
  ## if you have a pre-built package, set the url
  ## if you don't have a pre-built package, comment out the url
  ## then the package will be built from source
  ##
  ## If distributable.url is present, build, provides, and test sections are ignored.
  ##
  ## available variables in the url
  ## {{.tag}}     : tag name       (e.g. v1.2.3)
  ## {{.version}} : version string (e.g. 1.2.3)
  ## {{.os}}      : [linux, darwin, windows]
  ## {{.arch}}    : [amd64, arm64]
  ##
  #url: https://github.com/machbase/neo-pkg-web-example/releases/download/{{ .tag }}/neo-pkg-web-example.zip

  ## github organization/repository
  ## currently supports only github
  github: machbase/neo-pkg-web-example

  ## archive file depth
  strip_components: 1

description: |
  This is a web example package for machbase-neo.
  Use this package as a template to create your own web application package.

## Leave this empty if the artifacts are independent of the platform.
## It supports linux/amd64, darwin/amd64, darwin/arm64, windows/amd64
platforms:
  # - linux/amd64
  # - darwin/amd64
  # - darwin/arm64
  # - windows/amd64

##
build:
  scripts:
    - run: |
        npm install
        npm run build
  env:
    - NODE_ENV=prd

provides:
  - build/

test:
  scripts:
    - run: |
        echo "Testing web example package..."

## Post install script
install:
  scripts:
    - run: |
        echo "Installing web example package..."
        $MACHBASE_NEO version
    - on: windows
      run: |
        echo "Installing web example package for Windows..."
        %MACHBASE_NEO% version

## Pre uninstall script
uninstall:
  scripts:
    - run: |
        echo "Uninstalling web example package..."
    - on: windows
      run: |
        echo "Uninstalling web example package for Windows..."
