
distributable:
  github: machbase/neo-cat
  strip_components: 2

description: |
  This is a neo add-on package for monitoring.
  It includes a web frontend and backend process.
  Use this package as a template to create your own frontend + backend application package.

platforms:
  - linux/amd64
  - linux/arm64
  - darwin/arm64
  - windows/amd64
  # - darwin/amd64

build:
  - run: |
    cd frontend
    npm install
    npm run build
    cd ..
    go mod download
    go build -o ./frontend/build/.backend/neo-cat .
    cp scripts/* ./frontend/build/.backend
    cp .backend.yml ./frontend/build
  - on: windows
    run: |
      cd frontend
      npm install
      npm run build
      cd ..
      go mod download
      go build -o .\frontend\build\.backend\neo-cat .
      cp scripts\*.* .\frontend\build\.backend
      cp .backend.yml .\frontend\build
  env:
    - NODE_ENV=prd

provides:
  - frontend/build/

test:
  script:
    - ./frontend/build/.backend/neo-cat --help

install:
  script:
    - echo "Installing neo-cat package..."
install_windows:
  script:
    - echo "Installing neo-cat package for Windows..."

uninstall:
  script:
    - echo "Uninstalling neo-cat package..."
uninstall_windows:
  script:
    - echo "Uninstalling neo-cat package for Windows..."
