
distributable:
  github: machbase/machbase
  strip_components: 1

description: |
  This is the documents for machbase-neo.

platforms:

build:
  script:
    - apt-get install -y golang-go
    - wget -O ${TMP}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb
    - dpkg -i ${TMP}/hugo.deb
    - npm install -g sass
    - npm install
    - hugo --gc --minify --baseURL "/"
  env:
    - TMP=/tmp
    - HUGO_VERSION=0.120.4
    - HUGO_ENV=production

provides:
  - public/

test:
  script:
    - echo "Testing..."

## Post install process
install:
  script:
    - echo "Installed..."

## Pre uninstall process
uninstall:
  script:
    - echo "Uninstalling..."
