name: rebuild-cache
on:
  push:
    paths:
      - .github/workflows/rebuild-cache.yml
  schedule:
    - cron: '30 2 * * *'

jobs:
  rebuild-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - run: go install github.com/machbase/neo-pkgdev@58532a4524d44919dcbeaa4d3d029278c26dc5fb
      - name: ProcessDiff
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ./tmp && \
          neo-pkgdev update --dir ./tmp && \
          neo-pkgdev rebuild-cache --dir ./tmp
