name: rebuild-cache
on:
  schedule:
    - cron: '15 * * * *'

jobs:
  rebuild-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - run: go install github.com/machbase/neo-pkgdev@1f2006852c01891c4dac6b439e8ac8d7eeb2e61f
      - name: ProcessDiff
        run: |
          neo-pkgdev rebuild-cache --dir .
