name: rebuild-cache
on:
  push:
    paths:
      - .github/workflows/rebuild-cache.yml
  schedule:
    - cron: '15 1 * * *'

jobs:
  rebuild-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - run: go install github.com/machbase/neo-pkgdev@9432bb4991394a59d40919695cab1d04db957191
      - name: ProcessDiff
        run: |
          neo-pkgdev rebuild-cache --dir .
