name: rebuild-cache
on:
  push:
    paths:
      - .github/workflows/rebuild-cache.yml
  schedule:
    - cron: '30 2 * * *'
  workflow_dispatch:

jobs:
  rebuild-cache:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - run: go install github.com/machbase/neo-pkgdev@17c3dcdbb07df5bbd5fe9f82b473a1c1063d940f
      - name: Rebuild Cache
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p ./tmp && \
          neo-pkgdev update --dir ./tmp --roster-branch test-pkg --log-level info && \
          neo-pkgdev rebuild-cache --dir ./tmp --roster-branch test-pkg --log-level info
